### ISSUE TITLE
gemspec example

### ISSUE THREAD

**Issue by noraj** [highb/pathspec-ruby#28]
Can you add a example of gemspec where some can define `spec.files =` without using `git ls-files` but still taking `gitignore` into consideration.

See https://stackoverflow.com/questions/11873294/determining-the-gems-list-of-files-for-the-specification/57341496

**Comment by highb** [comment]
I'd be happy to add that when I get a spare bit of time. You are also welcome to contribute an example, if you like. Thank you for using my gem and opening an issue! :)

**Comment by noraj** [comment]
@highb Actually I'm not using your gem. :grin:  I wanted to but didn't find the right way to do this with it. That's why I opened the issue: if I don't know how to do it maybe others don't not but just gave up. That's why an example of you will be welcomed.

**Comment by noraj** [comment]
Does it work with `bundle install --path vendor`? cf. https://github.com/bundler/bundler/issues/7318

**Comment by highb** [comment]
I haven't tested it with the `--path vendor` flag but if you test it out and find that it doesn't work please open an issue and I can update the docs to have a working example. In the meanwhile, I'm closing this issue.

**Comment by noraj** [comment]
Since 2019 things have changed.

1) `--path vendor` is deprecated now.

```
bundle install --path vendor/bundle
```

must be changed into

```
bundle config set --local path 'vendor/bundle'
bundle install 
````

2) Yes the right way way is to use `Dir[]` (eg. https://github.com/noraj/haiti/blob/46c354819383514714e75d8b9eb889df7b5e468b/haiti.gemspec#L16-L17) manually (without taking .gitignore into consideration) it's still possible to use tricky ways to take gitignore into account for very advanced and complex projects.
