### ISSUE TITLE
Some missing bits according to the license

### ISSUE THREAD

**Issue by lelutin** [highb/pathspec-ruby#32]
Hello,

While inspecting the codebase for preparing a debian package with it, I saw that there were some details that were missing according to the license that you've chosen for the codebase:

* There should be a NOTICE file at the top
* each source code file should have a short header comment that mentions the license and a copyright attribution

To find out more details about the two points, you can check out the following URL: https://infra.apache.org/apply-license.html

**Comment by lelutin** [comment]
I was corrected by somebody else.. the presence of those elements are optional and the document specifically is a guideline for Apache developers.

sorry for the useless noise

**Comment by highb** [comment]
Thank you for looking into it and bring diligent enough to resolve it
yourself! I appreciate that you were paying close enough attention to
detail that you noticed this. Please do not hesitate to reach out in the
future if you notice something else that is amiss.
